# Generated by Django 5.1.3 on 2024-11-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id_appointment', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentsServices',
            fields=[
                ('id_appointment_service', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'appointments_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('id_appointment_status', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'appointment_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkshopsService',
            fields=[
                ('id_workshop_service', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'workshops_services',
                'managed': False,
            },
        ),
    ]
