# Generated by Django 5.1.3 on 2024-11-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrands',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'car_brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id_model', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'car_models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=15, unique=True)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'colors',
                'managed': False,
            },
        ),
    ]
